config/routes.rb
Gofish::Application.routes.draw do
  resources :licenses

  resources :registrations

  resources :reports

  get 'admin' => 'home#admin', as: :admin
  get 'checkreg' => 'licenses#check_license'

  get 'registration/textpost' => 'registrations#create_from_text'
  get 'report/textpost' => 'reports#create_from_text'

  post 'approve' => 'registrations#approve'
  post 'licenseapprove' => 'licenses#approve'
  post 'resolvereport' => 'reports#resolve'

  get 'confirmation' => 'home#confirmation', as: :confirmation
  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def admin
    @licenses_new = License.where('status != 2')
    @licenses_approved = License.where('status = 2')
    @registrations_new = Registration.where('status != 2')
    @registrations_approved = Registration.where('status = 2')
    @reports = Report.all
  end

  def confirmation
  	@type = params['type']
  end

end

app/views/home/admin.html.erb
<div class="row">
    <div class="one-third column section"></div>
    <div class="two-thirds column" id="welcomeheader">
      <p class="welcome">Welcome, Chalenge Masakera! You have
      <p><a href="#"><%= pluralize(@registrations_new.length, 'registration request') %></a>
      <p><a href="#"><%= pluralize(@licenses_new.length, 'license request') %></a></p>
      <p><a href="#"><%= pluralize(@reports.length, 'report') %> of illegal fishing</a></p>
    </div>
  </div>


  <div class="tabs">
      <ul class="tab-links">
          <li class="active"><a href="#tab1">Registrations</a></li>
          <li><a href="#tab2">Licenses</a></li>
          <li><a href="#tab3">Reports</a></li>
      </ul>
   
      <div class="tab-content">
          <div id="tab1" class="tab active">
              <p class="table-title">New Requests</p>
              <table class="regtable">
                <thead>
                  <tr>
                    <th>Status</th>
                    <th>Case ID</th>
                    <th>Date Requested</th>
                    <th>Name</th>
                    <th>Location</th>
                    <th></th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <% @registrations_new.each do |registration| %>
                      <tr>
                        <td><%= registration.status_text %></td>
                        <td><%= registration.id %></td>
                        <td><%= registration.created_at %></td> 
                        <td><%= registration.name %></td>
                        <td><%= registration.location_desc %></td>
                        <td><%= link_to 'View', registration %></td>
                      </tr>
                    <% end %>
                </tbody>
              </table>
              </br>

              <p class="table-title">Approved Requests</p>
              <table class="regtable">
                <thead>
                  <tr>
                    <th>Registration Number</th>
                    <th>Case ID</th>
                    <th>Date Requested</th>
                    <th>Name</th>
                    <th>Location</th>
                    <th></th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <% @registrations_approved.each do |registration| %>
                      <tr>
                        <td><%= registration.registration_number %></td>
                        <td><%= registration.id %></td>
                        <td><%= registration.created_at %></td> 
                        <td><%= registration.name %></td>
                        <td><%= registration.location_desc %></td>
                        <td><%= link_to 'View', registration %></td>
                      </tr>
                    <% end %>
                </tbody>
              </table>
          </div>
   
          <div id="tab2" class="tab">
              <p class="table-title">New Requests</p>
              <table class="regtable">
                <thead>
                  <tr>
                    <th>Status</th>
                    <th>Case ID</th>
                    <th>Date Requested</th>
                    <th>Fish Type</th>
                    <th>Location</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <% @licenses_new.each do |license| %>
                      <tr>
                        <td><%= license.status_text %></td>
                        <td><%= license.id %></td>
                        <td><%= license.created_at %></td> 
                        <td><%= license.fish_type_text %></td>
                        <td><%= license.location_desc %></td>
                        <td><%= link_to 'View', license %></td>
                      </tr>
                    <% end %>
                </tbody>
              </table>
              </br>
              <p class="table-title">Approved Requests</p>
              <table class="regtable">
                <thead>
                  <tr>
                    <th>Status</th>
                    <th>Case ID</th>
                    <th>Date Requested</th>
                    <th>Fish Type</th>
                    <th>Location</th>
                    <th>Fish Type</th>
                  </tr>
                </thead>
                <tbody>
                  <% @licenses_approved.each do |license| %>
                      <tr>
                        <td><%= license.status_text %></td>
                        <td><%= license.id %></td>
                        <td><%= license.created_at %></td> 
                        <td><%= license.fish_type_text %></td>
                        <td><%= license.location_desc %></td>
                        <td><%= link_to 'View', license %></td>
                      </tr>
                    <% end %>
                </tbody>
              </table>
          </div>
   
          <div id="tab3" class="tab">
              <p class="table-title">Reports</p>
              <table class="regtable">
              <thead>
                <tr>
                  <th>Status</th>
                  <th>Date</th>
                  <th>Location</th>
                  <th>Comments</th>
                  <th>Thumbnail</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @reports.each do |report| %>
                      <tr>
                        <td><%= report.status_text %></td>
                        <td><%= report.created_at %></td>
                        <td><%= report.location_desc || "" %></td> 
                        <td><%= report.comments || "" %></td>
                        <td style="vertical-align:middle">
                         <% if not report.photo_url.nil? %>
                            <img src="<%= '/data/' + report.photo_url %>" style="height:60px" >
                          <% else %>
                            No image available
                          <% end %>
                        </td>
                        <td><%= link_to 'View', report %></td>
                      </tr>
                    <% end %>
              </tbody>
              </table>
          </div>
      </div>
  </div>

app/views/home/confirmation.html.erb
<div class="10 columns center">
<p>
<h3>Thank you</h3>
<br>
<% if @type == 'license' %>
Thank you for submitting your licensing request. You will receive any updates via text message or phone call.	
<% elsif @type == 'registration' %>
Thank you for submitting your registration request. You will receive any updates via text message or phone call.
<% else %>
Thank you for submitting your report.
<% end %>
</p>
</div>

app/views/home/index.html.erb
	
<div class="sixteen columns center">
	<div><%= link_to image_tag('register.jpg', alt: 'Register a Vessel'), new_registration_path %>
	</div>
	<div><%= link_to image_tag('license.jpg', alt: 'New License'), new_license_path %></a>
	</div>
	<div><%= link_to image_tag('report.jpg', alt: 'Report Illegal Fishing'), new_report_path %>
	</div>
</div>